import Head from "next/head";

const Header = () => {
	return (
		<>
			<Head>
				<title>Rick & Morty x HA</title>
				<meta
					name="description"
					content="Generated by create next app. Authored by Merrill"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
		</>
	);
};
export default Header;
